CREATE TABLE actor
(
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	birthYear SMALLINT
);

CREATE TABLE movie
(
	id SERIAL PRIMARY KEY,
	title VATCHAR(100) NOT NULL,
	runtime SMALLINT,
	year SMALLINT
);

CREATE TABLE actor_movie
(
	id SERIAL PRIMARY KEY,
	actor_id INT NOT NULL REFERENCES actor(id),
	movie_id INT NOT NULL REFERENCES movie(id),
);